### ISSUE TITLE
3.0 roadmap

### ISSUE THREAD

**Issue by rmoriz** [rmoriz/knife-digital_ocean#83]
- [ ] get rid of VCR, just use RSpec to stub/mock DropletKit. It's their offical gem, we don't want to deal with the implementation anymore.
- [ ] support Floating IPs
- [ ] cleanup lots of code (DRY, RuboCop)
- [ ] current code coverage metrics are wrong, don't simulate coverage we don't have.
- [ ] Chef 12 only
- [ ] support JSON output

my WIP branch:
https://github.com/rmoriz/knife-digital_ocean/tree/rmoriz/3.0.0

**Comment by patcon** [comment]
Would be awesome to allow human-readable names to be used in a few places, rather than the numeric IDs (ie. droplet create/destroy/rebuild, include key flags). The plugin could error out if the names are not unique
